### ISSUE TITLE
Erro CEP Geral

### ISSUE THREAD

**Issue by Lukaum** [rjarouche/buscaviacep#1]
Ao colocar um CEP geral (XXX-000) é dado um erro, não retornando a cidade e nem o estado (somente um erro = 1 dentro do array). Isso está correto?

**Comment by rjarouche** [comment]
De acordo com o site do serviço https://viacep.com.br/ 

> Quando consultado um CEP de formato válido, porém inexistente, por exemplo: "99999999", o retorno conterá um valor de "erro" igual a "true". Isso significa que o CEP consultado não foi encontrado na base de dados.

O que aconteceu é que o Cep Geral não está cadastrado no ViaCep.
Está classe apenas acessa a base de dados e trás os resultados.
Sobre a inclusão desses cep's entre em contato com o ViaCep através de https://viacep.com.br/contato/


Ps: Fiz um teste com o CEP geral de Viçosa 36570-000 e realmente retorna o erro 1, já o específico 36570-001 funciona normalmente.
